[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "immrax"
version = "0.1.0"
dependencies = [
    "numpy<2",
    "scipy",
    "tqdm",
    "shapely",
    "matplotlib",
    "tabulate",
    "sympy",
    "sympy2jax",
	"jax",
    "jaxtyping",
    "diffrax",
    "equinox",
    "immutabledict",
    "jax_verify@git+https://github.com/Akash-Harapanahalli/jax_verify.git",
	"linrax"
]
